/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	scheme "github.com/networkmachinery/networkmachinery-operators/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EndpointKindsGetter has a method to return a EndpointKindInterface.
// A group's client should implement this interface.
type EndpointKindsGetter interface {
	EndpointKinds() EndpointKindInterface
}

// EndpointKindInterface has methods to work with EndpointKind resources.
type EndpointKindInterface interface {
	Create(*v1alpha1.EndpointKind) (*v1alpha1.EndpointKind, error)
	Update(*v1alpha1.EndpointKind) (*v1alpha1.EndpointKind, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EndpointKind, error)
	List(opts v1.ListOptions) (*v1alpha1.EndpointKindList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EndpointKind, err error)
	EndpointKindExpansion
}

// endpointKinds implements EndpointKindInterface
type endpointKinds struct {
	client rest.Interface
}

// newEndpointKinds returns a EndpointKinds
func newEndpointKinds(c *NetworkmachineryV1alpha1Client) *endpointKinds {
	return &endpointKinds{
		client: c.RESTClient(),
	}
}

// Get takes name of the endpointKind, and returns the corresponding endpointKind object, and an error if there is any.
func (c *endpointKinds) Get(name string, options v1.GetOptions) (result *v1alpha1.EndpointKind, err error) {
	result = &v1alpha1.EndpointKind{}
	err = c.client.Get().
		Resource("endpointkinds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EndpointKinds that match those selectors.
func (c *endpointKinds) List(opts v1.ListOptions) (result *v1alpha1.EndpointKindList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EndpointKindList{}
	err = c.client.Get().
		Resource("endpointkinds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested endpointKinds.
func (c *endpointKinds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("endpointkinds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a endpointKind and creates it.  Returns the server's representation of the endpointKind, and an error, if there is any.
func (c *endpointKinds) Create(endpointKind *v1alpha1.EndpointKind) (result *v1alpha1.EndpointKind, err error) {
	result = &v1alpha1.EndpointKind{}
	err = c.client.Post().
		Resource("endpointkinds").
		Body(endpointKind).
		Do().
		Into(result)
	return
}

// Update takes the representation of a endpointKind and updates it. Returns the server's representation of the endpointKind, and an error, if there is any.
func (c *endpointKinds) Update(endpointKind *v1alpha1.EndpointKind) (result *v1alpha1.EndpointKind, err error) {
	result = &v1alpha1.EndpointKind{}
	err = c.client.Put().
		Resource("endpointkinds").
		Name(endpointKind.Name).
		Body(endpointKind).
		Do().
		Into(result)
	return
}

// Delete takes name of the endpointKind and deletes it. Returns an error if one occurs.
func (c *endpointKinds) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("endpointkinds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *endpointKinds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("endpointkinds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched endpointKind.
func (c *endpointKinds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EndpointKind, err error) {
	result = &v1alpha1.EndpointKind{}
	err = c.client.Patch(pt).
		Resource("endpointkinds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
