/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	scheme "github.com/networkmachinery/networkmachinery-operators/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkSourceEndpointsGetter has a method to return a NetworkSourceEndpointInterface.
// A group's client should implement this interface.
type NetworkSourceEndpointsGetter interface {
	NetworkSourceEndpoints() NetworkSourceEndpointInterface
}

// NetworkSourceEndpointInterface has methods to work with NetworkSourceEndpoint resources.
type NetworkSourceEndpointInterface interface {
	Create(*v1alpha1.NetworkSourceEndpoint) (*v1alpha1.NetworkSourceEndpoint, error)
	Update(*v1alpha1.NetworkSourceEndpoint) (*v1alpha1.NetworkSourceEndpoint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.NetworkSourceEndpoint, error)
	List(opts v1.ListOptions) (*v1alpha1.NetworkSourceEndpointList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkSourceEndpoint, err error)
	NetworkSourceEndpointExpansion
}

// networkSourceEndpoints implements NetworkSourceEndpointInterface
type networkSourceEndpoints struct {
	client rest.Interface
}

// newNetworkSourceEndpoints returns a NetworkSourceEndpoints
func newNetworkSourceEndpoints(c *NetworkmachineryV1alpha1Client) *networkSourceEndpoints {
	return &networkSourceEndpoints{
		client: c.RESTClient(),
	}
}

// Get takes name of the networkSourceEndpoint, and returns the corresponding networkSourceEndpoint object, and an error if there is any.
func (c *networkSourceEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	result = &v1alpha1.NetworkSourceEndpoint{}
	err = c.client.Get().
		Resource("networksourceendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkSourceEndpoints that match those selectors.
func (c *networkSourceEndpoints) List(opts v1.ListOptions) (result *v1alpha1.NetworkSourceEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkSourceEndpointList{}
	err = c.client.Get().
		Resource("networksourceendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkSourceEndpoints.
func (c *networkSourceEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("networksourceendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a networkSourceEndpoint and creates it.  Returns the server's representation of the networkSourceEndpoint, and an error, if there is any.
func (c *networkSourceEndpoints) Create(networkSourceEndpoint *v1alpha1.NetworkSourceEndpoint) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	result = &v1alpha1.NetworkSourceEndpoint{}
	err = c.client.Post().
		Resource("networksourceendpoints").
		Body(networkSourceEndpoint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a networkSourceEndpoint and updates it. Returns the server's representation of the networkSourceEndpoint, and an error, if there is any.
func (c *networkSourceEndpoints) Update(networkSourceEndpoint *v1alpha1.NetworkSourceEndpoint) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	result = &v1alpha1.NetworkSourceEndpoint{}
	err = c.client.Put().
		Resource("networksourceendpoints").
		Name(networkSourceEndpoint.Name).
		Body(networkSourceEndpoint).
		Do().
		Into(result)
	return
}

// Delete takes name of the networkSourceEndpoint and deletes it. Returns an error if one occurs.
func (c *networkSourceEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("networksourceendpoints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkSourceEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("networksourceendpoints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched networkSourceEndpoint.
func (c *networkSourceEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	result = &v1alpha1.NetworkSourceEndpoint{}
	err = c.client.Patch(pt).
		Resource("networksourceendpoints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
