apiVersion: v1
kind: ServiceAccount
metadata:
  name: networkdelay-test-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: networkdelay-test-controller
    helm.sh/chart: networkdelay-test-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
