// +build !ignore_autogenerated

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Event) DeepCopyInto(out *Event) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Event.
func (in *Event) DeepCopy() *Event {
	if in == nil {
		return nil
	}
	out := new(Event)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsConfig) DeepCopyInto(out *EventsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsConfig.
func (in *EventsConfig) DeepCopy() *EventsConfig {
	if in == nil {
		return nil
	}
	out := new(EventsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flow.
func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastOperation) DeepCopyInto(out *LastOperation) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastOperation.
func (in *LastOperation) DeepCopy() *LastOperation {
	if in == nil {
		return nil
	}
	out := new(LastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringEndpoint) DeepCopyInto(out *MonitoringEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringEndpoint.
func (in *MonitoringEndpoint) DeepCopy() *MonitoringEndpoint {
	if in == nil {
		return nil
	}
	out := new(MonitoringEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConnectivityTest) DeepCopyInto(out *NetworkConnectivityTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConnectivityTest.
func (in *NetworkConnectivityTest) DeepCopy() *NetworkConnectivityTest {
	if in == nil {
		return nil
	}
	out := new(NetworkConnectivityTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConnectivityTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConnectivityTestList) DeepCopyInto(out *NetworkConnectivityTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkConnectivityTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConnectivityTestList.
func (in *NetworkConnectivityTestList) DeepCopy() *NetworkConnectivityTestList {
	if in == nil {
		return nil
	}
	out := new(NetworkConnectivityTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConnectivityTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConnectivityTestSpec) DeepCopyInto(out *NetworkConnectivityTestSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]NetworkDestinationEndpoint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConnectivityTestSpec.
func (in *NetworkConnectivityTestSpec) DeepCopy() *NetworkConnectivityTestSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkConnectivityTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConnectivityTestStatus) DeepCopyInto(out *NetworkConnectivityTestStatus) {
	*out = *in
	if in.TestStatus != nil {
		in, out := &in.TestStatus, &out.TestStatus
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConnectivityTestStatus.
func (in *NetworkConnectivityTestStatus) DeepCopy() *NetworkConnectivityTestStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkConnectivityTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDestinationEndpoint) DeepCopyInto(out *NetworkDestinationEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDestinationEndpoint.
func (in *NetworkDestinationEndpoint) DeepCopy() *NetworkDestinationEndpoint {
	if in == nil {
		return nil
	}
	out := new(NetworkDestinationEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkEvent) DeepCopyInto(out *NetworkEvent) {
	*out = *in
	out.Flow = in.Flow
	out.Event = in.Event
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkEvent.
func (in *NetworkEvent) DeepCopy() *NetworkEvent {
	if in == nil {
		return nil
	}
	out := new(NetworkEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMonitor) DeepCopyInto(out *NetworkMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMonitor.
func (in *NetworkMonitor) DeepCopy() *NetworkMonitor {
	if in == nil {
		return nil
	}
	out := new(NetworkMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMonitorList) DeepCopyInto(out *NetworkMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMonitorList.
func (in *NetworkMonitorList) DeepCopy() *NetworkMonitorList {
	if in == nil {
		return nil
	}
	out := new(NetworkMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMonitorSpec) DeepCopyInto(out *NetworkMonitorSpec) {
	*out = *in
	out.MonitoringEndpoint = in.MonitoringEndpoint
	if in.Flows != nil {
		in, out := &in.Flows, &out.Flows
		*out = make([]Flow, len(*in))
		copy(*out, *in)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]Threshold, len(*in))
		copy(*out, *in)
	}
	out.EventsConfig = in.EventsConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMonitorSpec.
func (in *NetworkMonitorSpec) DeepCopy() *NetworkMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMonitorStatus) DeepCopyInto(out *NetworkMonitorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMonitorStatus.
func (in *NetworkMonitorStatus) DeepCopy() *NetworkMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNotification) DeepCopyInto(out *NetworkNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNotification.
func (in *NetworkNotification) DeepCopy() *NetworkNotification {
	if in == nil {
		return nil
	}
	out := new(NetworkNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNotificationList) DeepCopyInto(out *NetworkNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNotificationList.
func (in *NetworkNotificationList) DeepCopy() *NetworkNotificationList {
	if in == nil {
		return nil
	}
	out := new(NetworkNotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkNotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNotificationSpec) DeepCopyInto(out *NetworkNotificationSpec) {
	*out = *in
	out.Event = in.Event
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNotificationSpec.
func (in *NetworkNotificationSpec) DeepCopy() *NetworkNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSourceEndpoint) DeepCopyInto(out *NetworkSourceEndpoint) {
	*out = *in
	if in.SourceSelector != nil {
		in, out := &in.SourceSelector, &out.SourceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSourceEndpoint.
func (in *NetworkSourceEndpoint) DeepCopy() *NetworkSourceEndpoint {
	if in == nil {
		return nil
	}
	out := new(NetworkSourceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingIPEndpoint) DeepCopyInto(out *PingIPEndpoint) {
	*out = *in
	out.PingResult = in.PingResult
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingIPEndpoint.
func (in *PingIPEndpoint) DeepCopy() *PingIPEndpoint {
	if in == nil {
		return nil
	}
	out := new(PingIPEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingPodEndpoint) DeepCopyInto(out *PingPodEndpoint) {
	*out = *in
	out.PodParams = in.PodParams
	out.PingResult = in.PingResult
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingPodEndpoint.
func (in *PingPodEndpoint) DeepCopy() *PingPodEndpoint {
	if in == nil {
		return nil
	}
	out := new(PingPodEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingResult) DeepCopyInto(out *PingResult) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingResult.
func (in *PingResult) DeepCopy() *PingResult {
	if in == nil {
		return nil
	}
	out := new(PingResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingServiceEndpoint) DeepCopyInto(out *PingServiceEndpoint) {
	*out = *in
	if in.ServiceResults != nil {
		in, out := &in.ServiceResults, &out.ServiceResults
		*out = make([]PingPodEndpoint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingServiceEndpoint.
func (in *PingServiceEndpoint) DeepCopy() *PingServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(PingServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingStatus) DeepCopyInto(out *PingStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PingIPEndpoints != nil {
		in, out := &in.PingIPEndpoints, &out.PingIPEndpoints
		*out = make([]PingIPEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.PingPodEndpoints != nil {
		in, out := &in.PingPodEndpoints, &out.PingPodEndpoints
		*out = make([]PingPodEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.PingServiceEndpoint != nil {
		in, out := &in.PingServiceEndpoint, &out.PingServiceEndpoint
		*out = make([]PingServiceEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingStatus.
func (in *PingStatus) DeepCopy() *PingStatus {
	if in == nil {
		return nil
	}
	out := new(PingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodParams) DeepCopyInto(out *PodParams) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodParams.
func (in *PodParams) DeepCopy() *PodParams {
	if in == nil {
		return nil
	}
	out := new(PodParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(LastOperation)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Threshold) DeepCopyInto(out *Threshold) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Threshold.
func (in *Threshold) DeepCopy() *Threshold {
	if in == nil {
		return nil
	}
	out := new(Threshold)
	in.DeepCopyInto(out)
	return out
}
