/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkMonitorLister helps list NetworkMonitors.
type NetworkMonitorLister interface {
	// List lists all NetworkMonitors in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkMonitor, err error)
	// Get retrieves the NetworkMonitor from the index for a given name.
	Get(name string) (*v1alpha1.NetworkMonitor, error)
	NetworkMonitorListerExpansion
}

// networkMonitorLister implements the NetworkMonitorLister interface.
type networkMonitorLister struct {
	indexer cache.Indexer
}

// NewNetworkMonitorLister returns a new NetworkMonitorLister.
func NewNetworkMonitorLister(indexer cache.Indexer) NetworkMonitorLister {
	return &networkMonitorLister{indexer: indexer}
}

// List lists all NetworkMonitors in the indexer.
func (s *networkMonitorLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkMonitor, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkMonitor))
	})
	return ret, err
}

// Get retrieves the NetworkMonitor from the index for a given name.
func (s *networkMonitorLister) Get(name string) (*v1alpha1.NetworkMonitor, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networkmonitor"), name)
	}
	return obj.(*v1alpha1.NetworkMonitor), nil
}
