/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkNotificationLister helps list NetworkNotifications.
type NetworkNotificationLister interface {
	// List lists all NetworkNotifications in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkNotification, err error)
	// Get retrieves the NetworkNotification from the index for a given name.
	Get(name string) (*v1alpha1.NetworkNotification, error)
	NetworkNotificationListerExpansion
}

// networkNotificationLister implements the NetworkNotificationLister interface.
type networkNotificationLister struct {
	indexer cache.Indexer
}

// NewNetworkNotificationLister returns a new NetworkNotificationLister.
func NewNetworkNotificationLister(indexer cache.Indexer) NetworkNotificationLister {
	return &networkNotificationLister{indexer: indexer}
}

// List lists all NetworkNotifications in the indexer.
func (s *networkNotificationLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkNotification, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkNotification))
	})
	return ret, err
}

// Get retrieves the NetworkNotification from the index for a given name.
func (s *networkNotificationLister) Get(name string) (*v1alpha1.NetworkNotification, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networknotification"), name)
	}
	return obj.(*v1alpha1.NetworkNotification), nil
}
