/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePingStatuses implements PingStatusInterface
type FakePingStatuses struct {
	Fake *FakeNetworkmachineryV1alpha1
	ns   string
}

var pingstatusesResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "pingstatuses"}

var pingstatusesKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "PingStatus"}

// Get takes name of the pingStatus, and returns the corresponding pingStatus object, and an error if there is any.
func (c *FakePingStatuses) Get(name string, options v1.GetOptions) (result *v1alpha1.PingStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pingstatusesResource, c.ns, name), &v1alpha1.PingStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PingStatus), err
}

// List takes label and field selectors, and returns the list of PingStatuses that match those selectors.
func (c *FakePingStatuses) List(opts v1.ListOptions) (result *v1alpha1.PingStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pingstatusesResource, pingstatusesKind, c.ns, opts), &v1alpha1.PingStatusList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PingStatusList), err
}

// Watch returns a watch.Interface that watches the requested pingStatuses.
func (c *FakePingStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pingstatusesResource, c.ns, opts))

}

// Create takes the representation of a pingStatus and creates it.  Returns the server's representation of the pingStatus, and an error, if there is any.
func (c *FakePingStatuses) Create(pingStatus *v1alpha1.PingStatus) (result *v1alpha1.PingStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pingstatusesResource, c.ns, pingStatus), &v1alpha1.PingStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PingStatus), err
}

// Update takes the representation of a pingStatus and updates it. Returns the server's representation of the pingStatus, and an error, if there is any.
func (c *FakePingStatuses) Update(pingStatus *v1alpha1.PingStatus) (result *v1alpha1.PingStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pingstatusesResource, c.ns, pingStatus), &v1alpha1.PingStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PingStatus), err
}

// Delete takes name of the pingStatus and deletes it. Returns an error if one occurs.
func (c *FakePingStatuses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pingstatusesResource, c.ns, name), &v1alpha1.PingStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePingStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pingstatusesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PingStatusList{})
	return err
}

// Patch applies the patch and returns the patched pingStatus.
func (c *FakePingStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PingStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pingstatusesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PingStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PingStatus), err
}
