/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkConnectivityTests implements NetworkConnectivityTestInterface
type FakeNetworkConnectivityTests struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networkconnectivitytestsResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networkconnectivitytests"}

var networkconnectivitytestsKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkConnectivityTest"}

// Get takes name of the networkConnectivityTest, and returns the corresponding networkConnectivityTest object, and an error if there is any.
func (c *FakeNetworkConnectivityTests) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkconnectivitytestsResource, name), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// List takes label and field selectors, and returns the list of NetworkConnectivityTests that match those selectors.
func (c *FakeNetworkConnectivityTests) List(opts v1.ListOptions) (result *v1alpha1.NetworkConnectivityTestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkconnectivitytestsResource, networkconnectivitytestsKind, opts), &v1alpha1.NetworkConnectivityTestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkConnectivityTestList{ListMeta: obj.(*v1alpha1.NetworkConnectivityTestList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkConnectivityTestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkConnectivityTests.
func (c *FakeNetworkConnectivityTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkconnectivitytestsResource, opts))
}

// Create takes the representation of a networkConnectivityTest and creates it.  Returns the server's representation of the networkConnectivityTest, and an error, if there is any.
func (c *FakeNetworkConnectivityTests) Create(networkConnectivityTest *v1alpha1.NetworkConnectivityTest) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkconnectivitytestsResource, networkConnectivityTest), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// Update takes the representation of a networkConnectivityTest and updates it. Returns the server's representation of the networkConnectivityTest, and an error, if there is any.
func (c *FakeNetworkConnectivityTests) Update(networkConnectivityTest *v1alpha1.NetworkConnectivityTest) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkconnectivitytestsResource, networkConnectivityTest), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkConnectivityTests) UpdateStatus(networkConnectivityTest *v1alpha1.NetworkConnectivityTest) (*v1alpha1.NetworkConnectivityTest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networkconnectivitytestsResource, "status", networkConnectivityTest), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// Delete takes name of the networkConnectivityTest and deletes it. Returns an error if one occurs.
func (c *FakeNetworkConnectivityTests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networkconnectivitytestsResource, name), &v1alpha1.NetworkConnectivityTest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkConnectivityTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkconnectivitytestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkConnectivityTestList{})
	return err
}

// Patch applies the patch and returns the patched networkConnectivityTest.
func (c *FakeNetworkConnectivityTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkconnectivitytestsResource, name, pt, data, subresources...), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}
