/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEndpointKinds implements EndpointKindInterface
type FakeEndpointKinds struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var endpointkindsResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "endpointkinds"}

var endpointkindsKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "EndpointKind"}

// Get takes name of the endpointKind, and returns the corresponding endpointKind object, and an error if there is any.
func (c *FakeEndpointKinds) Get(name string, options v1.GetOptions) (result *v1alpha1.EndpointKind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(endpointkindsResource, name), &v1alpha1.EndpointKind{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointKind), err
}

// List takes label and field selectors, and returns the list of EndpointKinds that match those selectors.
func (c *FakeEndpointKinds) List(opts v1.ListOptions) (result *v1alpha1.EndpointKindList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(endpointkindsResource, endpointkindsKind, opts), &v1alpha1.EndpointKindList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointKindList), err
}

// Watch returns a watch.Interface that watches the requested endpointKinds.
func (c *FakeEndpointKinds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(endpointkindsResource, opts))
}

// Create takes the representation of a endpointKind and creates it.  Returns the server's representation of the endpointKind, and an error, if there is any.
func (c *FakeEndpointKinds) Create(endpointKind *v1alpha1.EndpointKind) (result *v1alpha1.EndpointKind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(endpointkindsResource, endpointKind), &v1alpha1.EndpointKind{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointKind), err
}

// Update takes the representation of a endpointKind and updates it. Returns the server's representation of the endpointKind, and an error, if there is any.
func (c *FakeEndpointKinds) Update(endpointKind *v1alpha1.EndpointKind) (result *v1alpha1.EndpointKind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(endpointkindsResource, endpointKind), &v1alpha1.EndpointKind{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointKind), err
}

// Delete takes name of the endpointKind and deletes it. Returns an error if one occurs.
func (c *FakeEndpointKinds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(endpointkindsResource, name), &v1alpha1.EndpointKind{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEndpointKinds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(endpointkindsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EndpointKindList{})
	return err
}

// Patch applies the patch and returns the patched endpointKind.
func (c *FakeEndpointKinds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EndpointKind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(endpointkindsResource, name, pt, data, subresources...), &v1alpha1.EndpointKind{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointKind), err
}
