/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkSourceEndpoints implements NetworkSourceEndpointInterface
type FakeNetworkSourceEndpoints struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networksourceendpointsResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networksourceendpoints"}

var networksourceendpointsKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkSourceEndpoint"}

// Get takes name of the networkSourceEndpoint, and returns the corresponding networkSourceEndpoint object, and an error if there is any.
func (c *FakeNetworkSourceEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networksourceendpointsResource, name), &v1alpha1.NetworkSourceEndpoint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSourceEndpoint), err
}

// List takes label and field selectors, and returns the list of NetworkSourceEndpoints that match those selectors.
func (c *FakeNetworkSourceEndpoints) List(opts v1.ListOptions) (result *v1alpha1.NetworkSourceEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networksourceendpointsResource, networksourceendpointsKind, opts), &v1alpha1.NetworkSourceEndpointList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSourceEndpointList), err
}

// Watch returns a watch.Interface that watches the requested networkSourceEndpoints.
func (c *FakeNetworkSourceEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networksourceendpointsResource, opts))
}

// Create takes the representation of a networkSourceEndpoint and creates it.  Returns the server's representation of the networkSourceEndpoint, and an error, if there is any.
func (c *FakeNetworkSourceEndpoints) Create(networkSourceEndpoint *v1alpha1.NetworkSourceEndpoint) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networksourceendpointsResource, networkSourceEndpoint), &v1alpha1.NetworkSourceEndpoint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSourceEndpoint), err
}

// Update takes the representation of a networkSourceEndpoint and updates it. Returns the server's representation of the networkSourceEndpoint, and an error, if there is any.
func (c *FakeNetworkSourceEndpoints) Update(networkSourceEndpoint *v1alpha1.NetworkSourceEndpoint) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networksourceendpointsResource, networkSourceEndpoint), &v1alpha1.NetworkSourceEndpoint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSourceEndpoint), err
}

// Delete takes name of the networkSourceEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeNetworkSourceEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networksourceendpointsResource, name), &v1alpha1.NetworkSourceEndpoint{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkSourceEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networksourceendpointsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkSourceEndpointList{})
	return err
}

// Patch applies the patch and returns the patched networkSourceEndpoint.
func (c *FakeNetworkSourceEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkSourceEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networksourceendpointsResource, name, pt, data, subresources...), &v1alpha1.NetworkSourceEndpoint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSourceEndpoint), err
}
