/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkDelayTests implements NetworkDelayTestInterface
type FakeNetworkDelayTests struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networkdelaytestsResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networkdelaytests"}

var networkdelaytestsKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkDelayTest"}

// Get takes name of the networkDelayTest, and returns the corresponding networkDelayTest object, and an error if there is any.
func (c *FakeNetworkDelayTests) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkDelayTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkdelaytestsResource, name), &v1alpha1.NetworkDelayTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkDelayTest), err
}

// List takes label and field selectors, and returns the list of NetworkDelayTests that match those selectors.
func (c *FakeNetworkDelayTests) List(opts v1.ListOptions) (result *v1alpha1.NetworkDelayTestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkdelaytestsResource, networkdelaytestsKind, opts), &v1alpha1.NetworkDelayTestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkDelayTestList{ListMeta: obj.(*v1alpha1.NetworkDelayTestList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkDelayTestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkDelayTests.
func (c *FakeNetworkDelayTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkdelaytestsResource, opts))
}

// Create takes the representation of a networkDelayTest and creates it.  Returns the server's representation of the networkDelayTest, and an error, if there is any.
func (c *FakeNetworkDelayTests) Create(networkDelayTest *v1alpha1.NetworkDelayTest) (result *v1alpha1.NetworkDelayTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkdelaytestsResource, networkDelayTest), &v1alpha1.NetworkDelayTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkDelayTest), err
}

// Update takes the representation of a networkDelayTest and updates it. Returns the server's representation of the networkDelayTest, and an error, if there is any.
func (c *FakeNetworkDelayTests) Update(networkDelayTest *v1alpha1.NetworkDelayTest) (result *v1alpha1.NetworkDelayTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkdelaytestsResource, networkDelayTest), &v1alpha1.NetworkDelayTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkDelayTest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkDelayTests) UpdateStatus(networkDelayTest *v1alpha1.NetworkDelayTest) (*v1alpha1.NetworkDelayTest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networkdelaytestsResource, "status", networkDelayTest), &v1alpha1.NetworkDelayTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkDelayTest), err
}

// Delete takes name of the networkDelayTest and deletes it. Returns an error if one occurs.
func (c *FakeNetworkDelayTests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networkdelaytestsResource, name), &v1alpha1.NetworkDelayTest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkDelayTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkdelaytestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkDelayTestList{})
	return err
}

// Patch applies the patch and returns the patched networkDelayTest.
func (c *FakeNetworkDelayTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkDelayTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkdelaytestsResource, name, pt, data, subresources...), &v1alpha1.NetworkDelayTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkDelayTest), err
}
