/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkTrafficShapers implements NetworkTrafficShaperInterface
type FakeNetworkTrafficShapers struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networktrafficshapersResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networktrafficshapers"}

var networktrafficshapersKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkTrafficShaper"}

// Get takes name of the networkTrafficShaper, and returns the corresponding networkTrafficShaper object, and an error if there is any.
func (c *FakeNetworkTrafficShapers) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkTrafficShaper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networktrafficshapersResource, name), &v1alpha1.NetworkTrafficShaper{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkTrafficShaper), err
}

// List takes label and field selectors, and returns the list of NetworkTrafficShapers that match those selectors.
func (c *FakeNetworkTrafficShapers) List(opts v1.ListOptions) (result *v1alpha1.NetworkTrafficShaperList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networktrafficshapersResource, networktrafficshapersKind, opts), &v1alpha1.NetworkTrafficShaperList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkTrafficShaperList{ListMeta: obj.(*v1alpha1.NetworkTrafficShaperList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkTrafficShaperList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkTrafficShapers.
func (c *FakeNetworkTrafficShapers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networktrafficshapersResource, opts))
}

// Create takes the representation of a networkTrafficShaper and creates it.  Returns the server's representation of the networkTrafficShaper, and an error, if there is any.
func (c *FakeNetworkTrafficShapers) Create(networkTrafficShaper *v1alpha1.NetworkTrafficShaper) (result *v1alpha1.NetworkTrafficShaper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networktrafficshapersResource, networkTrafficShaper), &v1alpha1.NetworkTrafficShaper{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkTrafficShaper), err
}

// Update takes the representation of a networkTrafficShaper and updates it. Returns the server's representation of the networkTrafficShaper, and an error, if there is any.
func (c *FakeNetworkTrafficShapers) Update(networkTrafficShaper *v1alpha1.NetworkTrafficShaper) (result *v1alpha1.NetworkTrafficShaper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networktrafficshapersResource, networkTrafficShaper), &v1alpha1.NetworkTrafficShaper{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkTrafficShaper), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkTrafficShapers) UpdateStatus(networkTrafficShaper *v1alpha1.NetworkTrafficShaper) (*v1alpha1.NetworkTrafficShaper, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networktrafficshapersResource, "status", networkTrafficShaper), &v1alpha1.NetworkTrafficShaper{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkTrafficShaper), err
}

// Delete takes name of the networkTrafficShaper and deletes it. Returns an error if one occurs.
func (c *FakeNetworkTrafficShapers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networktrafficshapersResource, name), &v1alpha1.NetworkTrafficShaper{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkTrafficShapers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networktrafficshapersResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkTrafficShaperList{})
	return err
}

// Patch applies the patch and returns the patched networkTrafficShaper.
func (c *FakeNetworkTrafficShapers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkTrafficShaper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networktrafficshapersResource, name, pt, data, subresources...), &v1alpha1.NetworkTrafficShaper{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkTrafficShaper), err
}
