/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkConnectivities implements NetworkConnectivityInterface
type FakeNetworkConnectivities struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networkconnectivitiesResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networkconnectivities"}

var networkconnectivitiesKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkConnectivityTest"}

// Get takes name of the networkConnectivity, and returns the corresponding networkConnectivity object, and an error if there is any.
func (c *FakeNetworkConnectivities) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkconnectivitiesResource, name), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// List takes label and field selectors, and returns the list of NetworkConnectivities that match those selectors.
func (c *FakeNetworkConnectivities) List(opts v1.ListOptions) (result *v1alpha1.NetworkConnectivityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkconnectivitiesResource, networkconnectivitiesKind, opts), &v1alpha1.NetworkConnectivityList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkConnectivityList{ListMeta: obj.(*v1alpha1.NetworkConnectivityList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkConnectivityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkConnectivities.
func (c *FakeNetworkConnectivities) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkconnectivitiesResource, opts))
}

// Create takes the representation of a networkConnectivity and creates it.  Returns the server's representation of the networkConnectivity, and an error, if there is any.
func (c *FakeNetworkConnectivities) Create(networkConnectivity *v1alpha1.NetworkConnectivityTest) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkconnectivitiesResource, networkConnectivity), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// Update takes the representation of a networkConnectivity and updates it. Returns the server's representation of the networkConnectivity, and an error, if there is any.
func (c *FakeNetworkConnectivities) Update(networkConnectivity *v1alpha1.NetworkConnectivityTest) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkconnectivitiesResource, networkConnectivity), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}

// Delete takes name of the networkConnectivity and deletes it. Returns an error if one occurs.
func (c *FakeNetworkConnectivities) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networkconnectivitiesResource, name), &v1alpha1.NetworkConnectivityTest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkConnectivities) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkconnectivitiesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkConnectivityList{})
	return err
}

// Patch applies the patch and returns the patched networkConnectivity.
func (c *FakeNetworkConnectivities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkconnectivitiesResource, name, pt, data, subresources...), &v1alpha1.NetworkConnectivityTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkConnectivityTest), err
}
